m = model('testForControlInQuotes.model');
expLabel = { ...
    'Equation for X', ...
    'Equation for Y', ...
    'Equation for Z', ...
    };
actLabel = get(m,'labels');
myassert(actLabel,expLabel);


