m = model('testBracketsInQuotes.model');

% Descriptions of variables.
actDescript = get(m,'description');
expDescript = struct( ...
    'x','Variable x ([%])', ...
    'y','(Variable y)', ...
    'z','Variable z' ...
    );
myassert(actDescript,expDescript);

% Equation labels.
actLabel = get(m,'label');
expLabel = { ...
    '[Equation x]((', ...
    '{Equation {y', ...
    'Equation} z}', ...
    };
myassert(actLabel,expLabel);
