function default = bkw()
% bkw  [Not a public function] Default options for bkw class.
%
% Backend IRIS function.
% No help provided.

% -IRIS Toolbox.
% -Copyright (c) 2007-2014 IRIS Solutions Team.

%**************************************************************************

default = struct();

default.bkw = { ...
    'assign',[],@(x) isempty(x) || isstruct(x), ...
    'saveas','',@ischar, ...
    'std',1,@(x) is.numericscalar(x) && x >= 0, ...
    };

default.estimate = { ...
    'display','iter',@(x) is.anychar(x,{'off','none','final','iter'}), ...
    'filter',{},@(x) isempty(x) || (iscell(x) && iscellstr(x(1:2:end))), ...
    'initval','struct',@(x) any(strcmpi(x,{'struct','model'})), ...
    'maxiter',1000,@(isArg)is.numericscalar(isArg), ...
    'maxfunevals',5000,@(isArg)is.numericscalar(isArg), ...
    'optimset',[],@(x) isempty(x) || isstruct(x) || (iscell(x) && iscellstr(x(1:2:end))), ...
    'tolx',1e-10,@(isArg)is.numericscalar(isArg), ...
    'tolfun',1e-10,@(isArg)is.numericscalar(isArg), ...
    };

default.kalman = { ...
    'ahead',1,@(x) is.numericscalar(x) && x > 0 && round(x) == x, ...
    'optimset',{},@(x) iscell(x) && iscellstr(x(1:2:end)), ...
    'relative',true,@(isArg)is.logicalscalar(isArg), ...
    };

default.simulate = { ...
    'deviation',false,@(isArg)is.logicalscalar(isArg), ...
    'enbloc',false,@(isArg)is.logicalscalar(isArg), ...
    'esttime',false,@(isArg)is.logicalscalar(isArg), ...
    'ndraw',1,@(x) is.numericscalar(x) && x >= 1 && x == round(x), ...
    'optimset',{},@(x) iscell(x) && iscellstr(x(1:2:end)), ...
    'plan',[],@(x) isempty(x) || isa(x,'plan'), ...
    'progress',false,@(isArg)is.logicalscalar(isArg), ...
    'residuals,residual','data',@(x) isequal(x,'data') || is.func(x), ...
    'solvefor','endogenous',@(x) any(strcmpi(x,{'endogenous','residuals'})), ...
    'solver','lsqnonlin',@(x) is.anychar(x,{'lsqnonlin','fsolve'}), ...
    };

end