function Def = estimateobj()
% estimateobj  [Not a public function] Default options for estimateobj class functions.
%
% Backend IRIS function.
% No help provided.

% -IRIS Toolbox.
% -Copyright (c) 2007-2014 IRIS Solutions Team.

%--------------------------------------------------------------------------

Def.myestimate = { ...
    'display','iter',@(x) is.anychari(x,{'iter','final','none','off'}), ...
    'epspower',1/2,@isnumeric, ...
    'initval','struct',@(x) isempty(x) || isstruct(x) || is.anychari(x,{'struct','model'}), ...
    'maxiter',500,@(x) is.numericscalar(x) && x >= 0, ...
    'maxfunevals',2000,@(x) is.numericscalar(x) && x > 0, ...
    'optimset',{},@(x) isempty(x) || isstruct(x) || (iscell(x) && iscellstr(x(1:2:end))), ...
    'penalty',0,@(x) is.numericscalar(x) && x >= 0, ...
    'evallik',true,@is.logicalscalar, ...
    'evalpprior,evalppriors',true,@is.logicalscalar, ...
    'evalsprior,evalspriors',true,@is.logicalscalar, ...
    'solver,optimiser,optimizer','fmin',@(x) (ischar(x) && is.anychari(x,{'fmin','lsqnonlin','pso'})) ...
    || iscell(x) || is.func(x), ...
    'tolfun',1e-6,@(x) isnumeric(x) && x > 0, ...
    'tolx',1e-6,@(x) isnumeric(x) && x > 0, ...
    'updateinit',[],@(x) isempty(x) || isstruct(x), ...
    };

end