function Def = latex()
% latex  [Not a public function] Default options for latex package functions.
%
% Backend IRIS function.
% No help provided.

% The IRIS Toolbox.
% -Copyright (c) 2007-2014 IRIS Solutions Team.

%--------------------------------------------------------------------------

Def = struct();

Def.epstopdf = {...
    'display',false,@islogical,...
    };

Def.compilepdf = { ...
    'cd',false,@(isArg)is.logicalscalar(isArg), ...
    'display',true,@(isArg)is.logicalscalar(isArg), ...
    'echo',false,@(isArg)is.logicalscalar(isArg), ...
    'maxrerun',5,@(isArg)is.numericscalar(isArg), ...
    'minrerun',1,@(isArg)is.numericscalar(isArg), ...
    };

Def.publish = { ...
    'author','',@ischar, ...
    'cleanup',true,@(isArg)is.logicalscalar(isArg), ...
    'closeall',true,@(isArg)is.logicalscalar(isArg), ...
    'date','\today',@ischar, ...
    'deletetempfiles,cleanup',[],@(x) isempty(x) || is.logicalscalar(x), ...
    'display',true,@(isArg)is.logicalscalar(isArg), ...
    'evalcode',true,@(isArg)is.logicalscalar(isArg), ...
    'event','',@ischar, ...
    'figurescale',1,@(x) is.numericscalar(x) && x > 0, ...
    'figurewidth','4in',@ischar, ...
    'irisversion',true,@(isArg)is.logicalscalar(isArg), ...
    'linespread','auto',@(x) (ischar(x) && strcmpi(x,'auto')) ...
    || is.numericscalar(x) && x > 0, ...
    'matlabversion',true,@(isArg)is.logicalscalar(isArg), ...
    'numbered',true,@(isArg)is.logicalscalar(isArg), ...
    'papersize','letterpaper', ...
    @(x) isequal(x,'a4paper') || isequal(x,'letterpaper'), ...
    'preamble','',@ischar, ...
    'package',{},@(x) iscellstr(x) || ischar(x) || isempty(x), ...
    'template','paper',@(x) ischar(x) && any(strcmpi(x,{'paper','present'})), ...
    'textscale',0.70,@(isArg)is.numericscalar(isArg), ...
    'toc',true,@(isArg)is.logicalscalar(isArg), ...
    'usenewfigure',false,@(isArg)is.logicalscalar(isArg), ...
    };

end