function Def = optim()
% optim  [Not a public function] Default options for optim package.
%
% Backend IRIS function.
% No help provided.

% -IRIS Toolbox.
% -Copyright (c) 2007-2014 IRIS Solutions Team.

%--------------------------------------------------------------------------

Def = struct();

Def.pso = { ...
    'CognitiveAttraction', 0.5, @(x) is.numericscalar(x) && x>=0 && x<=1, ...
    'ConstrBoundary','reflect', @(x) is.anychari(x,{'soft','reflect','absorb'}), ...
    'Display','iter', @(x) is.anychari(x,{'off','iter','final'}), ...
    'DemoMode','off', @(x) is.anychari(x,{'off','fast','pretty','on'}), ...
    'FitnessLimit', -Inf, @(x) is.numericscalar(x), ...
    'Generations', 1000, @(x) is.numericscalar(x) && x>0, ...
    'HybridFcn', false, @(x) is.logicalscalar(x) || is.func(x) ...
    || iscell(x) || ischar(x), ...
    'IncludeInitialValue', true, @(x) islogical(x), ...
    'InitialPopulation', [], @(x) isnumeric(x), ...
    'InitialPopulationUsesBounds', false, @(x) islogical(x), ...
    'InitialVelocities', [], @(x) isnumeric(x), ...
    'KnownMin', [], @(x) is.numericscalar(x) || isempty(x), ...
    'PlotFcns', {}, @is.cellfunc, ...
    'PlotInterval', 1, @(x) is.intscalar(x) && x>0, ...
    'PopInitRange', [], @(x) isnumeric(x) || isempty(x), ...
    'PopulationSize', 40, @(x) is.intscalar(x) && x>0, ...
    'SocialAttraction', 1.25, @(x) is.numericscalar(x), ...
    'StallGenLimit', 50, @(x) is.intscalar(x) && x>0, ...
    'TimeLimit', Inf, @(x) is.numericscalar(x) && x>0, ...
    'TolCon', 1e-6, @(x) is.numericscalar(x) && x>0, ...
    'TolFun', 1e-6, @(x) is.numericscalar(x) && x>0, ...
    'VelocityLimit', Inf, @(x) is.numericscalar(x) && x>0, ...
    'UpdateInterval', 5, @(x) is.numericscalar(x) && x>0, ...
    'UseParallel', false, @is.logicalscalar, ...
    };

end


