function Def = poster()
% poster  [Not a public function] Default options for poster class.
%
% Backend IRIS function.
% No help provided.

% -IRIS Toolbox.
% -Copyright (c) 2007-2014 IRIS Solutions Team.

%#ok<*CCAT>

%--------------------------------------------------------------------------

Def = struct();

Def.arwm = { ...
    'adaptscale',1,@(x) is.numericscalar(x) && x >= 0, ...
    'adaptproposalcov',0.5,@(x) is.numericscalar(x) && x >= 0, ...
    'burnin',0.10,@(x) is.numericscalar(x) ...
    && ((x >= 0 && x < 1) || (x > 1 && x == round(x))), ...
    'esttime',false,@is.logicalscalar, ...
    'firstPrefetch,firstParallel',1,@is.intscalar, ...
    'gamma',0.8,@(x) is.numericscalar(x) ....
    && ( (x > 0.5 && x <= 1) || isnan(x) || isinf(x) ), ...
    'initscale',@auto,@(x) isequal(x,@auto) || (is.numericscalar(x) && x > 0), ...
    'lastadapt',Inf,@is.intscalar, ...
    'progress',false,@is.logicalscalar, ...
    'saveevery',Inf,@(x) is.intscalar(x) && x > 0, ...
    'saveas','',@ischar, ...
    'targetar',0.234,@(x) is.numericscalar(x) && x > 0 && x <= 0.5 ...
	'nstep,nsteps',1,@(x) is.intscalar(x) && x>0 ...
    };

Def.impsamp = { ...
    'progress',false,@is.logicalscalar, ...
    };

Def.regen = { ...
    'initialChainSize',0.1,@(x) is.numericscalar(x) && x > 0, ...
    };

Def.stats = { ...
    'esttime',false,@is.logicalscalar, ...
    'hpdicover',90,@(x) is.numericscalar(x) && x >= 0 && x <= 100, ...
    'histbins,histbin',50,@(x) isnintscalar(x) && x > 0, ...
    'mddgrid',0.1:0.1:0.9,@(x) isnumeric(x) && all(x(:) > 0 & x(:) < 1), ...
    'output','',@(x) ischar(x) || iscellstr(x), ...
    'progress',false,@is.logicalscalar, ...
    ...
    'chain',true,@is.logicalscalar, ...
    'cov',false,@is.logicalscalar, ...
    'mean',true,@is.logicalscalar, ...
    'median',false,@is.logicalscalar, ...
    'mode',false,@is.logicalscalar, ...
    'mdd,lmdd',true,@is.logicalscalar, ...
    'std',true,@is.logicalscalar, ...
    'hpdi',false,@(x) is.logicalscalar(x) || (is.numericscalar(x) && x > 0 && x < 100), ...
    'hist',true,@(x) is.logicalscalar(x) || (is.intscalar(x) && x > 0), ...
    'bounds',false,@is.logicalscalar, ...
    'ksdensity',false,@(x) is.logicalscalar(x) || isempty(x) || (is.intscalar(x) && x > 0), ...
    'prctile,pctile',[],@(x) isnumeric(x) && all(x(:) >= 0 & x(:) <= 100), ...
    };

end