function Def = qreport()
% qreport  [Not a public function] Default options for quick-report functions.
%
% Backend IRIS function
% No help provided.

% -IRIS Toolbox.
% -Copyright (c) 2007-2014 IRIS Solutions Team.

%--------------------------------------------------------------------------

Def = struct();

Def.qplot = {...
    'addclick',true,@(isArg)is.logicalscalar(isArg), ...
    'clear',[],@isnumeric, ...
    'drawnow',false,@islogical, ...
    'grid',true,@(isArg)is.logicalscalar(isArg), ...
    'highlight',[],@(x) isnumeric(x) ...
    || (iscell(x) && all(cellfun(@isnumeric,x))), ...
    'mark',{},@(x) iscell(x) || ischar(x), ...
    'prefix','P%g_',@ischar, ...
    'round',Inf,@(x) is.numericscalar(x) && x >= 0 && round(x) == x, ...
    'sstate',struct(),@(x) isempty(x) || isstruct(x) || isa(x,'model'), ...
    'style',struct(),@(x) isempty(x) || isstruct(x) || (iscellstr(x) && length(x) == 1), ...
    'tight',false,@(isArg)is.logicalscalar(isArg), ...
    'vline',[],@(x) isempty(x) || isnumeric(x), ...
    'zeroline',false,@(isArg)is.logicalscalar(isArg), ...
    };

Def.qreport = {...
    'addclick',true,@(isArg)is.logicalscalar(isArg), ...
    'caption,captions,title,titles',{},@(x) isempty(x) || iscellstr(x) || is.func(x), ...
    'clear',[],@isnumeric, ...
    'clone','',@ischar, ...
    'deviationfrom,deviationsfrom',[],@(x) isempty(x) || is.logicalscalar(x) || is.numericscalar(x), ...
    'deviationtimes,deviationstimes',1,@(isArg)is.numericscalar(isArg), ...
    'dbsave',{},@(x) iscell(x) && iscellstr(x(1:2:end)), ...
    'drawnow',false,@islogical, ...
    'grid',true,@(isArg)is.logicalscalar(isArg), ...
    'highlight',[],@(x) isnumeric(x) ...
    || (iscell(x) && all(cellfun(@isnumeric,x))), ...
    'interpreter','none',@(x) any(strcmpi(x,{'latex','tex','none'})), ...
    'mark',{},@iscellstr, ...
    'maxfigure',false,@(varargin)is.logicalscalar(varargin{:}), ...
    'overflow',false,@(isArg)is.logicalscalar(isArg), ...
    'pagenumber,pagenumbers',false,@(isArg)is.logicalscalar(isArg), ...    
    'plotfunc',@plot,@(x) (is.func(x) || ischar(x)) ...
    && any(strcmpi(char(x),{'plot','bar','stem','hist','plotpred','errorbar','plotcmp'})), ...
    'prefix','P%g_',@ischar, ...
    'round',Inf,@(x) is.numericscalar(x) && x >= 0 && round(x) == x, ...
    'saveas','',@ischar, ...
    'sstate',struct(),@(x) isempty(x) || isstruct(x) || isa(x,'model'), ...
    'style',struct(),@(x) isempty(x) || isstruct(x) || (iscellstr(x) && length(x) == 1), ...
    'subplot','auto',@(x) strcmpi(x,'auto') ...
    || (isnumeric(x) && length(x) == 2 && all(~isnan(x) & x > 0 & x == round(x))), ...
    'tight',false,@(isArg)is.logicalscalar(isArg), ...
    'transform',[],@(x) isempty(x) || is.func(x), ...
    'vline',[],@(x) isempty(x) || isnumeric(x), ...
    'xlabel','',@(x) ischar(x) || iscellstr(x), ...
    'ylabel','',@(x) ischar(x) || iscellstr(x), ...
    'zeroline',false,@(isArg)is.logicalscalar(isArg), ...
    };

Def.qstyle = { ...
    'cascade',true,@(isArg)is.logicalscalar(isArg), ...
    'offset',0,@(isArg)is.numericscalar(isArg), ...
    'warning',true,@(isArg)is.logicalscalar(isArg), ...
    };

end