m = model('testAutoexogenize.model');

% Values assigned to variables in model file.
actAssign = get(m,'autoexogenize');
expAssign = struct( ...
    'x','ex', ...
    'y','ey', ...
    'z','ez', ...
    'w','ew' ...
    );
myassert(actAssign,expAssign);
