m = model('testMultipleAssignment.model');

% Values assigned to variables in model file.
actAssign = get(m,'sstate');
expAssign = struct( ...
    'x',[1,2,3], ...
    'y',[4,5,6], ...
    'z',[1,1,1], ...
    'w',[NaN,NaN,NaN], ...
    'alp',[10,10,10], ...
    'bet',sin([1,2,3]) ...
    );
myassert(actAssign,expAssign);
